// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var delay;
    delay = '';
    $('nav > ul > li.menu').on({
      mouseenter: function(e) {
        if ($(window).width() > 768) {
          clearTimeout(delay);
          $('nav > ul > li').removeClass('on');
          $('nav > ul > li > ul').hide();
          return $(this).addClass('on');
        }
      },
      mouseleave: function(e) {
        if ($(window).width() > 768) {
          return delay = setTimeout((function() {
            $('nav > ul > li').removeClass('on');
            return $('nav > ul > li > ul').hide();
          }), 350);
        }
      },
      click: function(e) {
        var $this;
        if ($(window).width() < 768) {
          if ($(e.target).parent('li.menu').size() > 0) {
            $this = $(this);
            $(this).children('ul').slideToggle(300, function() {
              return $this.toggleClass('on');
            });
            e.preventDefault();
            return false;
          }
        }
      },
      tap: function(e) {
        var $this;
        if ($(e.target).parent('li.menu').size() > 0) {
          $this = $(this);
          $(this).children('ul').slideToggle(300, function() {
            return $this.toggleClass('on');
          });
          e.preventDefault();
          return false;
        }
      }
    });
    $('.error input, .error textarea, \
     .invalid input, .invalid textarea, \
     input.error, textarea.error, \
     input.invalid, textarea.invalid').on({
      click: function() {
        $(this).focus();
        return $(this).select();
      }
    });
    $('span.select select').each(function() {
      if ($(this).children('option').first().val() === '' && $(this).children('option').first().attr('selected')) {
        return $(this).addClass('unselected');
      } else {
        return $(this).removeClass('unselected');
      }
    });
    $('span.select select').on({
      change: function() {
        if ($(this).children('option').first().val() === '' && $(this).children('option').first().attr('selected')) {
          return $(this).addClass('unselected');
        } else {
          return $(this).removeClass('unselected');
        }
      }
    });
    $('.tabs > ul > li > a').not('.disabled').click(function(e) {
      var tabs;
      tabs = $(this).parents('.tabs');
      tabs.find('> ul li a').removeClass('active');
      $(this).addClass('active');
      tabs.children('div').removeClass('active');
      return tabs.children($(this).attr('href')).addClass('active');
    });
    $('.responsive').each(function(index, object) {
      var max, min, scale;
      scale = 10;
      min = 10;
      max = 200;
      scale = parseFloat($(this).attr('data-scale') || scale);
      min = parseFloat($(this).attr('data-min') || min);
      max = parseFloat($(this).attr('data-max') || max);
      return $(object).responsiveText({
        agressiveness: scale,
        minSize: min,
        maxSize: max
      });
    });
    $('.demo > .row > .column, \
     .demo > .row > .columns,\
     .demo > .row > .whole, \
     .demo > .row > .wholes, \
     .demo > .row > .half, \
     .demo > .row > .halves, \
     .demo > .row > .third, \
     .demo > .row > .thirds, \
     .demo > .row > .fourth, \
     .demo > .row > .fourths, \
     .demo > .row > .fifth, \
     .demo > .row > .fifths, \
     .demo > .row > .sixth, \
     .demo > .row > .sixths, \
     .demo > .row > .seventh,\
     .demo > .row > .sevenths, \
     .demo > .row > .eighth, \
     .demo > .row > .eighths, \
     .demo > .row > .ninth,  \
     .demo > .row > .ninths,  \
     .demo > .row > .tenth, \
     .demo > .row > .tenths, \
     .demo > .row > .eleventh,\
     .demo > .row > .elevenths, \
     .demo > .row > .twelfth,\
     .demo > .row > .twelfths').each(function() {
      $(this).attr('data-title', $(this).attr('class'));
      return $(this).attr('data-text', $(this).text());
    });
    return $('.demo > .row > .column, \
     .demo > .row > .columns,\
     .demo > .row > .whole, \
     .demo > .row > .wholes, \
     .demo > .row > .half, \
     .demo > .row > .halves, \
     .demo > .row > .third, \
     .demo > .row > .thirds, \
     .demo > .row > .fourth, \
     .demo > .row > .fourths, \
     .demo > .row > .fifth, \
     .demo > .row > .fifths, \
     .demo > .row > .sixth, \
     .demo > .row > .sixths, \
     .demo > .row > .seventh,\
     .demo > .row > .sevenths, \
     .demo > .row > .eighth, \
     .demo > .row > .eighths, \
     .demo > .row > .ninth,  \
     .demo > .row > .ninths,  \
     .demo > .row > .tenth, \
     .demo > .row > .tenths, \
     .demo > .row > .eleventh,\
     .demo > .row > .elevenths, \
     .demo > .row > .twelfth,\
     .demo > .row > .twelfths').hover((function() {
      return $(this).text($(this).attr("data-title"));
    }), function() {
      return $(this).text($(this).attr("data-text"));
    });
  });

  $(window).load(function() {
    return $('.slider').orbit();
  });

}).call(this);
