// Generated by CoffeeScript 1.4.0

/*
 * avgrund 0.1
 * http://lab.hakim.se/avgrund
 * MIT licensed
 *
 * Copyright (C) 2012 Hakim El Hattab, http://hakim.se
*/


(function() {
  var Avgrund;

  Avgrund = (function() {
    var activate, addClass, container, cover, currentState, deactivate, disableBlur, hide, onDocumentClick, onDocumentKeyUp, popup, removeClass, show;
    onDocumentKeyUp = function(event) {
      if (event.keyCode === 27) {
        return deactivate();
      }
    };
    onDocumentClick = function(event) {
      if (event.target === cover) {
        return deactivate();
      }
    };
    activate = function(state) {
      var currentState;
      document.addEventListener("keyup", onDocumentKeyUp, false);
      document.addEventListener("click", onDocumentClick, false);
      document.addEventListener("touchstart", onDocumentClick, false);
      removeClass(popup, currentState);
      addClass(popup, "no-transition");
      addClass(popup, state);
      setTimeout((function() {
        removeClass(popup, "no-transition");
        return addClass(container, "avgrund-active");
      }), 0);
      return currentState = state;
    };
    deactivate = function() {
      document.removeEventListener("keyup", onDocumentKeyUp, false);
      document.removeEventListener("click", onDocumentClick, false);
      document.removeEventListener("touchstart", onDocumentClick, false);
      removeClass(container, "avgrund-active");
      return removeClass(popup, "avgrund-popup-animate");
    };
    disableBlur = function() {
      return addClass(document.documentElement, "no-blur");
    };
    addClass = function(element, name) {
      return element.className = element.className.replace(/\s+$/g, "") + " " + name;
    };
    removeClass = function(element, name) {
      return element.className = element.className.replace(name, "");
    };
    show = function(selector) {
      var popup;
      popup = document.querySelector(selector);
      addClass(popup, "avgrund-popup-animate");
      activate();
      return this;
    };
    hide = function() {
      return deactivate();
    };
    container = document.documentElement;
    popup = document.querySelector(".avgrund-popup-animate");
    cover = document.querySelector(".avgrund-cover");
    currentState = null;
    container.className = container.className.replace(/\s+$/g, "") + " avgrund-ready";
    return {
      activate: activate,
      deactivate: deactivate,
      disableBlur: disableBlur,
      show: show,
      hide: hide
    };
  })();

}).call(this);
